//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalReservation.DAL.CarRentalReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int UserId { get; set; }
        public string UserFirstNamee { get; set; }
        public string UserLastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
